# Generated by Django 4.1 on 2022-08-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakeside', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='agbada',
            new_name='appetizer',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='gown',
            new_name='breakfast',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='native',
            new_name='dessert',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='suit',
            new_name='dinner',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='wedding_dress',
            new_name='drink',
        ),
        migrations.AddField(
            model_name='style',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='style',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
