# Generated by Django 4.1 on 2022-08-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakeside', '0002_rename_agbada_style_appetizer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_name', models.CharField(max_length=50)),
                ('inner_rep', models.CharField(max_length=50)),
                ('inner_image', models.ImageField(upload_to='inner')),
            ],
        ),
    ]
