# Generated by Django 4.1 on 2022-08-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakeside', '0003_inner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inner',
            name='inner_image',
            field=models.ImageField(blank=True, default='pix.jpeg', null=True, upload_to='inner'),
        ),
    ]
