# Generated by Django 4.1 on 2022-08-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakeside', '0004_alter_inner_inner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
