# Generated by Django 4.0.6 on 2022-08-31 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lakeside', '0006_alter_style_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('c_price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lakeside.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopcart',
                'verbose_name_plural': 'Shopcarts',
                'db_table': 'shopcart',
                'managed': True,
            },
        ),
    ]
